export const FORM_PROJECT = 'FORM_PROJECTS'
export const GET_PROJECTS = 'GET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const VALIDATE_FORM = 'VALIDATE_FORM'
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const PROJECT_ERROR = 'PROJECT_ERROR'

export const TODOS_PROJECT = 'TODOS_PROJECT'
export const ADD_TODO = 'ADD_TODO'
export const VALIDATE_TODO = 'VALIDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const ACTUAL_TODO = 'ACTUAL_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const CLEAN_TODO = 'CLEAN_TODO'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const REGISTER_OK = 'REGISTER_OK'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const GET_USER = 'GET_USER'
export const LOGIN_OK = 'LOGIN_OK'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'

