export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_OK = 'ADD_PRODUCT_OK'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const RETRIEVE_PRODUCTS = 'RETRIEVE_PRODUCTS'
export const RETRIEVE_PRODUCTS_OK = 'RETRIEVE_PRODUCTS_OK'
export const RETRIEVE_PRODUCTS_ERROR = 'RETRIEVE_PRODUCTS_ERROR'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_OK = 'DELETE_PRODUCT_OK'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const SELECT_EDIT_PRODUCT = 'SELECT_EDIT_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_OK = 'EDIT_PRODUCT_OK'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE ALERT'